
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GameConfig
{
public partial class Tables
{
    #region The Tables

    private PKJ.TLocalization m_TLocalization;
    public PKJ.TLocalization TLocalization 
    {
        get
        {
            if (m_TLocalization == null)
            {
                m_TLocalization = new PKJ.TLocalization(defaultLoader("pkj_tlocalization"));
                m_TLocalization.ResolveRef(this);
            }
            return m_TLocalization;
        }
        set
        {
            m_TLocalization = value;
            m_TLocalization.ResolveRef(this);
        }
    }

    #endregion

    System.Func<string, ByteBuf> defaultLoader;

    public Tables(System.Func<string, ByteBuf> loader)
    {
        SetDefaultLoader(loader);
        Init();
    }
    
    public void SetDefaultLoader(System.Func<string, ByteBuf> loader)
    {
        defaultLoader = null;
        defaultLoader = loader;
    }

    //public partial void Init();

    public void Init(){}
}

}
