
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.PKJ
{
public sealed partial class BeansTest : Luban.BeanBase
{
    public BeansTest(ByteBuf _buf) 
    {
        Type = _buf.ReadString();
    }

    public static BeansTest DeserializeBeansTest(ByteBuf _buf)
    {
        return new PKJ.BeansTest(_buf);
    }

    /// <summary>
    /// 类型
    /// </summary>
    public readonly string Type;
   
    public const int __ID__ = -1137402794;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Type:" + Type + ","
        + "}";
    }
}
}

