
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.PKJ
{
public sealed partial class Localization : Luban.BeanBase
{
    public Localization(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Type = _buf.ReadString();
        Describe = _buf.ReadString();
        English = _buf.ReadString();
        Chinese = _buf.ReadString();
        ChineseTraditional = _buf.ReadString();
        Japanese = _buf.ReadString();
    }

    public static Localization DeserializeLocalization(ByteBuf _buf)
    {
        return new PKJ.Localization(_buf);
    }

    /// <summary>
    /// Key
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// Type
    /// </summary>
    public readonly string Type;
    /// <summary>
    /// Desc
    /// </summary>
    public readonly string Describe;
    /// <summary>
    /// English
    /// </summary>
    public readonly string English;
    /// <summary>
    /// Chinese
    /// </summary>
    public readonly string Chinese;
    /// <summary>
    /// ChineseTraditional
    /// </summary>
    public readonly string ChineseTraditional;
    /// <summary>
    /// Japanese
    /// </summary>
    public readonly string Japanese;
   
    public const int __ID__ = -806746984;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "Type:" + Type + ","
        + "Describe:" + Describe + ","
        + "English:" + English + ","
        + "Chinese:" + Chinese + ","
        + "ChineseTraditional:" + ChineseTraditional + ","
        + "Japanese:" + Japanese + ","
        + "}";
    }
}
}

