
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.PKJ
{
public partial class TLocalization
{
    private readonly System.Collections.Generic.Dictionary<int, PKJ.Localization> _dataMap;
    private readonly System.Collections.Generic.List<PKJ.Localization> _dataList;
    
    public TLocalization(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, PKJ.Localization>(n);
        _dataList = new System.Collections.Generic.List<PKJ.Localization>(n);
        for(int i = n ; i > 0 ; --i)
        {
            PKJ.Localization _v;
            _v = global::GameConfig.PKJ.Localization.DeserializeLocalization(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, PKJ.Localization> DataMap => _dataMap;
    public System.Collections.Generic.List<PKJ.Localization> DataList => _dataList;

    public PKJ.Localization GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public PKJ.Localization Get(int key) => _dataMap[key];
    public PKJ.Localization this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

